### PR TITLE
aligned gain loss of function hierarchy

### PR DESCRIPTION
**Pull request by cameronmore**
addresses #164

### CODE REVIEW

**Comment by neilotte** [comment]
@cameronmore Can I ask you to address the conflicts on this branch?

**Comment by cameronmore** [comment]
@neilotte resolved

**Comment by neilotte** [comment]
@cameronmore Still seeing them unfortunately.

**Comment by cameronmore** [comment]
@neilotte if you can review it again, it will let me try to resolve them again

**Comment by mark-jensen** [comment]
@cameronmore your branch is 49 commits behind `develop` on the main CCO repo. Best practice dictates that you make sure your patch branches are current with the HEAD of whatever you are going to merge into. Conflicts need to be handled on your side first. If you need help, let one of us know

**Comment by cameronmore** [comment]
the only conflict is the 'generated at [timestamp]' that appears at the bottom of each owl file.

**Comment by mark-jensen** [comment]
Great, then fix the conflict.

**Review by mark-jensen — APPROVED** [review]

**Comment by mark-jensen** [comment]
@cameronmore Hold any attempt to fix until we sort this out across the repo since all PRs are showing conflicts.

**Pull request closed without merging**
