### PR TITLE
Definition of occurs at to be broadened #144

### PR DESCRIPTION
**Pull request by neilotte**
@johnbeve  Please review. 

Note: There is a related issue I hae flagged for the 2.0 release. See https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/320

### CODE REVIEW

**Comment by alanruttenberg** [comment]
I object to this change. For one thing you are retaining the IRI while changing what it is a subproperty of. For another, we have to have a discussion of whether spatial region should be every used as there is an ambiguity as to the difference between site and spatial region that will lead to divergent representation practices.

**Comment by neilotte** [comment]
@alanruttenberg can you say more regarding the spatial region ambiguity? The first objection I’m already tracking.

**Comment by alanruttenberg** [comment]
I generally advise not to represent spatial regions. The ambiguity has to do with understanding the criteria by which one would choose that an entity is a spatial region vs a site. What is that criteria? Both need to be defined in reference to something. Moreover spatial regions can not bear qualities, making it difficult to express things that need to be expressed. As an example, CCO defines major an minor axes of an ellipse as spatial regions vs me defining them as boundaries. As spatial regions we can not have a quality that is their length, that an information content entity would be about. As boundaries they can. Similarly axis of rotation, which needs to inhere in a relational quality in order to have a target for information about the angle between the rotational axes of two entities, or between the rotational axis and the equatorial plane.

**Comment by neilotte** [comment]
@alanruttenberg Thanks for explaining. I share your concern about spatial region. I think in the (distant) past, you and I have discussed a need to make this clearer to consumers of bfo2020. I have seen this become an issue in BFO-extending ontologies I've reviewed, where two separate ontologies build out place hierarchies under spatial region due to an unfamiliarity with sites. @johnbeve @alanruttenberg  Do you think there's a possibility of adding this as an editorial note to the OWL file (or including a pointer to such language)?

Secondly, @alanruttenberg, a question on how to read the implication of your comments: is it your contention that there should be no direct relation between processes and spatial regions?

**Comment by alanruttenberg** [comment]
Given that I don't think spatial regions should not be used in representations, there's no need for an direct link from a process to a spatial region. There's already a path via occupies-spatiotemporal-region > spatially-projects-onto.

Unsure about how to surface this in BFO. Would need consent of Barry. @johnbeve  your ideas?

**Comment by neilotte** [comment]
Given this branch now has issues with the repo restructure--and in light of other comments--I'll close this and mark the issue for 2.0.

**Pull request closed without merging**
