### PR TITLE
358 use of 'instance of' in definitions for four object properties

### LINKED ISSUE #358: Use of 'instance of' in definitions for four object properties
In #259, I noted a seeming problem involving the use of 'instance of' in the definition for **has member located in**--namely that 'an instance of some material entity' implies that a material entity can have instances. @mark-jensen agreed that this was a problem, and @cameronmore has now created a pull request that addresses both it and another worry I described in the comments.

However, I also noted in #259 that variants of this problem affect the definitions for seven other object properties. I plan to create a pull request that addresses the problem for four of them--**caused by**, **affects**, **is cause of**, and **is affected by**--while also putting their definitions into the favored form described by Mark in the comments, and I've created this issue to link it to.

(Note: I've left out **is temporal region of** because of the further concerns with its definition described in my #262, as well as **process started by** and **process starts** because their definitions also suffer from an additional problem.)

### PR DESCRIPTION
**Pull request by gregfowlerphd**
Fixes #358

### CODE REVIEW

**Comment by gregfowlerphd** [comment]
@cameronmore: Please review this pull request, which addresses my #358, if possible.

**Comment by gregfowlerphd** [comment]
Fixes #358

**Comment by mark-jensen** [comment]
@gregfowlerphd your branch is 78 commits behind the HEAD of `develop`.  Please update and resolve any conflicts. If you need help, please reach out to one of us.

**Comment by mark-jensen** [comment]
@gregfowlerphd Appreciate the quick response. Hold any attempt to fix until we sort this out across the repo since all PRs are showing conflicts.

**Comment by johnbeve** [comment]
@gregfowlerphd Please open a new request with the same changes; that'll be the easiest way to align.

**Pull request closed without merging**
