### PR TITLE
declared dcterms prefix in 7 modules

### PR DESCRIPTION
**Pull request by johnbeve**
Added dcterms prefix to 7 files per @swartik's issue [471](https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/471)

### CODE REVIEW

**Comment by johnbeve** [comment]
Incidentally, the declaration issue is why the build was broken; this PR should resolve the issue

FYSA @neilotte

**Review by neilotte — APPROVED** [review]

**Comment by mark-jensen** [comment]
Weird that it didn't cause an issue when I ran the exact command locally on Artifact before the fix was made.

**Comment by mark-jensen** [comment]
Closes #477

**Comment by mark-jensen** [comment]
Closes #471

**Pull request merged**
