### PR TITLE
AVATAR-452 Add Solid demo file to the list of indexed files

### PR DESCRIPTION
**Pull request by kaleb-himes**

### CODE REVIEW

**Comment by mark-jensen** [comment]
@kaleb-himes Why do we need a copy of the CUP ontology indexed here? Is the versioned one located [here](https://raw.githubusercontent.com/CommonCoreOntology/CommonUserProfile/master/CommonUserProfileOntology.ttl) not accessible?

**Comment by kaleb-himes** [comment]
@mark-jensen let's discuss on Tuesday. Cheers, KH

**Comment by kaleb-himes** [comment]
@mark-jensen,

Jacob is tracking See AVATAR-454 for pathing clarification. Jacob will be in touch once you and Bob are back.

- KH

**Comment by mark-jensen** [comment]
Stale, nothing to do

**Pull request closed without merging**
