### PR TITLE
asserted 'has value' data property and added definitions

### PR DESCRIPTION
**Pull request by cameronmore**
Implemented a change discussed in #188 and added definitions for data properties

### CODE REVIEW

**Comment by alanruttenberg** [comment]
'has value' means exactly the same thing as topDataProperty. All data properties have a range that is a data value, i.e an rdfs:Literal.

Also note the relation to the value specification proposal.

**Comment by neilotte** [comment]
@cameronmore  Per @alanruttenberg 's comment, seems cco:has_value should be deprecated. Concur?

**Comment by cameronmore** [comment]
I just want to tag @mark-jensen since he originally discussed this in #188

**Comment by swartik** [comment]
@neilotte cco:has_value is a new data property so it needn't be deprecated.

I do not think we are ready to introduce cco:has_value. Per issue #188, we still have not resolved its domain. The current set of CCO data properties all use IBE, which is not universally accepted as preferrable. As @alanruttenberg stated elsewhere (too many issues and discussions for me to find it quickly), we probably will have to delay this until 1.7.

**Comment by cameronmore** [comment]
I agree, introduction of new datatypes should be coordinated with @alanruttenberg 's value specification proposal and its design pattern. I will remove reference to it, and I will change the range of cco:has_text_value to an xsd:string or rdf:langString which solves the original reasoning error.

Related, this is an interesting proposal for the creation of [xsd:InternationalizedString](https://www.w3.org/2007/OWL/wiki/InternationalizedString#:~:text=Note%20that%20the%20lexical%20values,without%20any%20spaces%20between%20them.)

**Comment by neilotte** [comment]
@cameronmore In that case, can we close this PR?

**Comment by cameronmore** [comment]
I still changed the range of has_text_value which addresses the original issue raised in #188 by @swartik as well as added nominal definitions

**Review by neilotte — APPROVED** [review]
Good work @cameronmore. Approving.

**Comment by neilotte** [comment]
@mark-jensen -- Can you also review this? @cameronmore requested your review as well.

**Pull request merged**
