### PR TITLE
improved definitions per #358

### LINKED ISSUE #358: Use of 'instance of' in definitions for four object properties
In #259, I noted a seeming problem involving the use of 'instance of' in the definition for **has member located in**--namely that 'an instance of some material entity' implies that a material entity can have instances. @mark-jensen agreed that this was a problem, and @cameronmore has now created a pull request that addresses both it and another worry I described in the comments.

However, I also noted in #259 that variants of this problem affect the definitions for seven other object properties. I plan to create a pull request that addresses the problem for four of them--**caused by**, **affects**, **is cause of**, and **is affected by**--while also putting their definitions into the favored form described by Mark in the comments, and I've created this issue to link it to.

(Note: I've left out **is temporal region of** because of the further concerns with its definition described in my #262, as well as **process started by** and **process starts** because their definitions also suffer from an additional problem.)

### PR DESCRIPTION
**Pull request by gregfowlerphd**
Fixes #358

### CODE REVIEW

**Comment by gregfowlerphd** [comment]
@johnbeve: Done

**Comment by gregfowlerphd** [comment]
Well, it looks like my branch is behind on commits again. If I go back and make the changes again, do you think it will be reviewed soon enough so that the same problem doesn't arise?

@johnbeve @mark-jensen @neilotte

**Comment by cameronmore** [comment]
@gregfowlerphd The repo restructuring might have been the cause of the conflicts on the other branches, but these still look like they are able to merge easily.

**Comment by gregfowlerphd** [comment]
@cameronmore: Thanks, Cameron. :)

**Review by neilotte — APPROVED** [review]
Good eye @gregfowlerphd

**Comment by gregfowlerphd** [comment]
@neilotte: Thanks, Neil. :) I admit I'm still not entirely sold on using the "instance of" locution in these definitions but not in class definitions, but since that seemed to be the consensus choice (such as it were), I thought it best not to rock the boat.

**Pull request merged**
