### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by mark-jensen**
removed old directory ignores for outdated build process

### CODE REVIEW

**Review by oliviahobai — APPROVED** [review]
Looks good Mark, thank you

**Comment by cameronmore** [comment]
what do we think about adding back *.py? I was relying on it, but I can adjust if the group decides to drop it.
@johnbeve @neilotte

**Comment by swartik** [comment]
@mark-jensen Can you expand on what you mean by the outdated build process? The makefile still references a build directory.

**Comment by mark-jensen** [comment]
@cameronmore you can edit your local copy of .gitignore to ignore whatever you want. We are doing some house cleaning.

**Comment by mark-jensen** [comment]
> @mark-jensen Can you expand on what you mean by the outdated build process? 

those two directories were ones I used to store files during the generation and testing of CCO releases. I no longer use them so no need to have them ignored. I should have never pushed up my ignore needs to the repo anyways. 

>The makefile still references a build directory.

that is most likely a temp directory that gets created during a build process, which we are experimenting with now.

**Comment by johnbeve** [comment]
@cameronmore You were relying on python files not being tracked through versions?

**Comment by johnbeve** [comment]
@swartik, @mark-jensen is on the money, there is a temp build directory created as part of the build process

**Comment by cameronmore** [comment]
@johnbeve I was using a python file with RDFLib to more easily query the ontologies and test scripts rather than going through ROBOT

**Comment by swartik** [comment]
@johnbeve, yes, the build directory sticks around after I run make, and then git tells me it's not tracked. Hence my surprise that @mark-jensen removed it from the gitignore file. In any event, if the build process is still experimental, I'll sit tight until you pin it down.

**Comment by johnbeve** [comment]
@cameronmore I'm not seeing how the workflow you describe relies on ignoring .py files.

**Pull request merged**
